[package]
name = "domo"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.24"
reqwest = { version = "0.11", features = ["json"] }
futures = "0.3"
tokio = { version = "1", features = ["full"] }
clap = "3.0"
regex = "1.5"