[package]
name = "domo"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
futures = "0.3"
tokio = { version = "1", features = ["full"] }
rayon = "1.7.0"
clap = "3.0"
colored = "2.0.0"
select = "0.5"